version: "3.8"

services:
    web:
        build:
            context: ./
        image: 4syncostelo/rest-api
        container_name: rest-api
        ports:
            - "3000:3000"
        restart: on-failure
        depends_on:
            - db
        networks:
            - app_net

    db:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - app_net
    
networks:
    app_net:
        driver: bridge
  